name: Basic Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test help output
      run: |
        python cs2modrewrite.py -h
    - name: Test console output
      run: |
        python cs2modrewrite.py -i havex.profile -c http://127.0.0.1 -r http://google.com
    - name: Test file output
      run: |
          python cs2modrewrite.py -i havex.profile -c http://127.0.0.1 -r http://google.com -o htaccess.txt
      
